### ISSUE TITLE
Sample Code not working for SQL Server Debezium Connector

### ISSUE THREAD

**Issue by ummershervani** [confluentinc/commercial-workshops#9]
Hello @zacharydhamilton ,

Do you have an example for self managed connector for SQL Server ? I tried couple changes to the db section but couldn't get that to work coz there is no documentation for SQL Server. 
https://github.com/confluentinc/commercial-workshops/blob/master/series-microservices/workshop-connectors/docker-compose.yml

**Comment by zacharydhamilton** [comment]
Not currently. However, there is a [Debezium SQL Server CDC Source Connector](https://www.confluent.io/hub/debezium/debezium-connector-sqlserver) in Confluent Hub. You can create the connector image with a simple Dockerfile, and then reference that new connector image in the `docker-compose.yml`. 

The Dockerfile would be something like the following:

```
FROM confluentinc/cp-server-connect-base:6.0.1

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"
 
RUN confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:1.5.0
```

After building the image, just reference it in `docker-compose.yml`:

```
...
connect:
    image: <name of your new image>
    hostname: connect
    container_name: connect
...
```

Once the connector is running, you can use Confluent Control Center to configure it. 

Hope this helps.
